### ISSUE TITLE
Extended Frames not working

### ISSUE THREAD

**Issue by Duality4Y** [kobolt/usb-can#11]
Hello,
Thank you very much for this useful utility!!

I am using the usb-can dongle to debug connections with an STM32F103 using Standard frames and that works,
However I Want to use Extended frames, so I changed the source in such a way hoping to enable Extended frames:

```diff
diff --git a/canusb.c b/canusb.c
index d1aaba2..464b2cf 100644
--- a/canusb.c
+++ b/canusb.c
@@ -407,7 +407,7 @@ static int inject_data_frame(int tty_fd, const char *hex_id, const char *hex_dat
         binary_data[i]++;
     }
 
-    error = send_data_frame(tty_fd, CANUSB_FRAME_STANDARD, binary_id_lsb, binary_id_msb, binary_data, data_len);
+    error = send_data_frame(tty_fd, CANUSB_FRAME_EXTENDED, binary_id_lsb, binary_id_msb, binary_data, data_len);
   }
 
   return error;
@@ -606,7 +606,8 @@ int main(int argc, char *argv[])
     return EXIT_FAILURE;
   }
 
-  command_settings(tty_fd, speed, CANUSB_MODE_NORMAL, CANUSB_FRAME_STANDARD);
+  // command_settings(tty_fd, speed, CANUSB_MODE_NORMAL, CANUSB_FRAME_STANDARD);
+  command_settings(tty_fd, speed, CANUSB_MODE_NORMAL, CANUSB_FRAME_EXTENDED);
 
   if (inject_data == NULL) {
     /* Dumping mode (default). */

```

but it does not work and only produces standard frames

**Comment by Duality4Y** [comment]
The first  ~16 frames my dongle sends out are malformed the End of Frame is wrong
here is a capture with my logic analyzer:
![image](https://github.com/kobolt/usb-can/assets/1276401/cee03803-d4e0-4e83-aafe-b60e2d1e597c)
As you can see the End of Frame contains zeros where there should have been ones.
I am not sure if this is an issue with my dongle or with your code.

**Comment by Duality4Y** [comment]
I think send_data_frame needs to be edited to send correct ID information in-case of a Extended Frame
Because the usb-can analyzer protocol defines for Standard frame that 2 bytes are used for ID
Where as with Extended ID it is 4 bytes.

**Comment by kobolt** [comment]
The problem is probably in the code, if you can get it working then I will gladly accept a pull request!

**Comment by Duality4Y** [comment]
> The first ~16 frames my dongle sends out are malformed the End of Frame is wrong here is a capture with my logic analyzer: ![image](https://user-images.githubusercontent.com/1276401/283063945-cee03803-d4e0-4e83-aafe-b60e2d1e597c.png) As you can see the End of Frame contains zeros where there should have been ones. I am not sure if this is an issue with my dongle or with your code.

I already solved this issue, it happens when there is no node connected to the network to ACK the frame.
I'll see If I can do something with the code to add extended frames as I currently have access to a setup to full test that out :)

**Comment by kobolt** [comment]
I hope this is finally solved by the recent contribution.
