### ISSUE TITLE
Is it possible to send can messages using this driver?

### ISSUE THREAD

**Issue by mozcelikors** [kobolt/usb-can#3]
I understand that usb-can is merely configuring the device, but I am wondering if I can use it to send CAN messages to the bus. I can't seem to be seeing the message sent by "command_settings" function on the other end.
Is frame_send simply sending frame to TTY to configure the Analyzer, or is it sending a message to CAN-BUS directly?
If you can share your thoughts on this, I would appreciate it.
Thanks

**Comment by mozcelikors** [comment]
Hi, I was able to do it using the documentation in https://copperhilltech.com/blog/usbcan-analyzer-usb-to-can-bus-serial-protocol-definition/

**Comment by kobolt** [comment]
Right now this program is just a dumper/sniffer.
The only command sent to it, is used to configure it.
If you can manage to actually inject CAN messages, then that would be interesting. Please share the code if you are able to.

**Comment by kobolt** [comment]
Send function merged, and additional command line options added to use it.
Thanks for the effort.
