### ISSUE TITLE
usb-can firmware for stm32

### ISSUE THREAD

**Issue by Kosmonova** [kobolt/usb-can#9]
Hello.
I created firmware for usb-can. I readed, that many users have problem with damaging of usc-can because firmware. I had the same problem. For this reason I wrote my own program for this device for free using. Maybe it will be interesting for you. This is the link of my project https://github.com/Kosmonova/usb-can-firmware-stm32 My goal is sharing of codes between programmers and users. our code has also been useful to me in history.

**Comment by kobolt** [comment]
Not sure what I can do about this except add some information about your project into the README.md of this project.
